// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"Todo/pkg/api/handlers"
	"Todo/pkg/repository"
	"Todo/pkg/usecase"
)

// Injectors from wire.go:

func InitializeTaskApi() *handlers.TaskHandler {
	taskRepoInterfaces := repository.NewTaskRepository()
	taskUseCaseInterface := usecase.NewTaskUsecase(taskRepoInterfaces)
	taskHandler := handlers.NewTaskHandler(taskUseCaseInterface)
	return taskHandler
}

func InitializeUserApi() *handlers.UserHandler {
	userRepoInterfaces := repository.NewUserRepository()
	userUseCaseInterface := usecase.NewUserUsecase(userRepoInterfaces)
	userHandler := handlers.NewUserHandler(userUseCaseInterface)
	return userHandler
}
