// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"Todo/pkg/api/handlers"
	"Todo/pkg/repository"
	"Todo/pkg/usecase"
)

// Injectors from wire.go:

func InitializeHandlerApi() *handlers.Handler {
	repoInterfaces := repository.NewTodoRepository()
	useCaseInterface := usecase.NewUsecase(repoInterfaces)
	handler := handlers.NewHandler(useCaseInterface)
	return handler
}
